# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from spdkrpc import nvmecli_pb2 as spdkrpc_dot_nvmecli__pb2


class NvmeAgentServiceStub(object):
    """NvmeAgentService is a thin gRPC facade over go-spdk-helper NVMe initiator
    operations. It is intentionally limited to NVMe CLI / kernel state only.
    The agent does not access SPDK objects, so every RPC must carry all target
    information required to operate in the agent pod's own network namespace.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DiscoverTarget = channel.unary_unary(
                '/spdkrpc.NvmeAgentService/DiscoverTarget',
                request_serializer=spdkrpc_dot_nvmecli__pb2.NvmeDiscoverTargetRequest.SerializeToString,
                response_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeDiscoverTargetResponse.FromString,
                )
        self.ConnectTarget = channel.unary_unary(
                '/spdkrpc.NvmeAgentService/ConnectTarget',
                request_serializer=spdkrpc_dot_nvmecli__pb2.NvmeConnectTargetRequest.SerializeToString,
                response_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeConnectTargetResponse.FromString,
                )
        self.DisconnectTarget = channel.unary_unary(
                '/spdkrpc.NvmeAgentService/DisconnectTarget',
                request_serializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectTargetRequest.SerializeToString,
                response_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectTargetResponse.FromString,
                )
        self.DisconnectController = channel.unary_unary(
                '/spdkrpc.NvmeAgentService/DisconnectController',
                request_serializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectControllerRequest.SerializeToString,
                response_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectControllerResponse.FromString,
                )
        self.GetDevices = channel.unary_unary(
                '/spdkrpc.NvmeAgentService/GetDevices',
                request_serializer=spdkrpc_dot_nvmecli__pb2.NvmeGetDevicesRequest.SerializeToString,
                response_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeGetDevicesResponse.FromString,
                )
        self.GetSubsystems = channel.unary_unary(
                '/spdkrpc.NvmeAgentService/GetSubsystems',
                request_serializer=spdkrpc_dot_nvmecli__pb2.NvmeGetSubsystemsRequest.SerializeToString,
                response_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeGetSubsystemsResponse.FromString,
                )


class NvmeAgentServiceServicer(object):
    """NvmeAgentService is a thin gRPC facade over go-spdk-helper NVMe initiator
    operations. It is intentionally limited to NVMe CLI / kernel state only.
    The agent does not access SPDK objects, so every RPC must carry all target
    information required to operate in the agent pod's own network namespace.
    """

    def DiscoverTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectController(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubsystems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NvmeAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DiscoverTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverTarget,
                    request_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeDiscoverTargetRequest.FromString,
                    response_serializer=spdkrpc_dot_nvmecli__pb2.NvmeDiscoverTargetResponse.SerializeToString,
            ),
            'ConnectTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectTarget,
                    request_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeConnectTargetRequest.FromString,
                    response_serializer=spdkrpc_dot_nvmecli__pb2.NvmeConnectTargetResponse.SerializeToString,
            ),
            'DisconnectTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectTarget,
                    request_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectTargetRequest.FromString,
                    response_serializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectTargetResponse.SerializeToString,
            ),
            'DisconnectController': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectController,
                    request_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectControllerRequest.FromString,
                    response_serializer=spdkrpc_dot_nvmecli__pb2.NvmeDisconnectControllerResponse.SerializeToString,
            ),
            'GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevices,
                    request_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeGetDevicesRequest.FromString,
                    response_serializer=spdkrpc_dot_nvmecli__pb2.NvmeGetDevicesResponse.SerializeToString,
            ),
            'GetSubsystems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubsystems,
                    request_deserializer=spdkrpc_dot_nvmecli__pb2.NvmeGetSubsystemsRequest.FromString,
                    response_serializer=spdkrpc_dot_nvmecli__pb2.NvmeGetSubsystemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spdkrpc.NvmeAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NvmeAgentService(object):
    """NvmeAgentService is a thin gRPC facade over go-spdk-helper NVMe initiator
    operations. It is intentionally limited to NVMe CLI / kernel state only.
    The agent does not access SPDK objects, so every RPC must carry all target
    information required to operate in the agent pod's own network namespace.
    """

    @staticmethod
    def DiscoverTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spdkrpc.NvmeAgentService/DiscoverTarget',
            spdkrpc_dot_nvmecli__pb2.NvmeDiscoverTargetRequest.SerializeToString,
            spdkrpc_dot_nvmecli__pb2.NvmeDiscoverTargetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spdkrpc.NvmeAgentService/ConnectTarget',
            spdkrpc_dot_nvmecli__pb2.NvmeConnectTargetRequest.SerializeToString,
            spdkrpc_dot_nvmecli__pb2.NvmeConnectTargetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spdkrpc.NvmeAgentService/DisconnectTarget',
            spdkrpc_dot_nvmecli__pb2.NvmeDisconnectTargetRequest.SerializeToString,
            spdkrpc_dot_nvmecli__pb2.NvmeDisconnectTargetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spdkrpc.NvmeAgentService/DisconnectController',
            spdkrpc_dot_nvmecli__pb2.NvmeDisconnectControllerRequest.SerializeToString,
            spdkrpc_dot_nvmecli__pb2.NvmeDisconnectControllerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spdkrpc.NvmeAgentService/GetDevices',
            spdkrpc_dot_nvmecli__pb2.NvmeGetDevicesRequest.SerializeToString,
            spdkrpc_dot_nvmecli__pb2.NvmeGetDevicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubsystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spdkrpc.NvmeAgentService/GetSubsystems',
            spdkrpc_dot_nvmecli__pb2.NvmeGetSubsystemsRequest.SerializeToString,
            spdkrpc_dot_nvmecli__pb2.NvmeGetSubsystemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
